#server.port=9090
## MySQL Database Connection
#spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
#spring.datasource.username=root
#spring.datasource.password=12345
#
## MySQL Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA Settings
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.show-sql=true

server.port=${SERVER_PORT:9090}

spring.security.user.name=admin
spring.security.user.password=password